version: 0.2

env:
  shell: bash
  variables:
    CI: true
    PIP_DISABLE_PIP_VERSION_CHECK: true
    PIP_QUIET: true
    NODE_OPTIONS: '--max-old-space-size=8192'

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - aws codeartifact login --tool pip --repository dgx-shared-pypi-repo --domain dgx-shared-codeartifact --domain-owner $ACCOUNT_ID
      - pip install pipx==$PIPX_PACKAGE_VERSION
      # Add pipx binaries to path
      - export PATH="$PATH:/root/.local/bin"
      - aws codeartifact login --tool npm --repository dgx-shared-npm-repo --domain dgx-shared-codeartifact --domain-owner $ACCOUNT_ID
      - pipx install dgx-devops-pipeline-library==$PIPELINE_LIBRARY_PACKAGE_VERSION
  pre_build:
    commands:
      - dgx-pipeline build-init
  build:
    commands:
      - dgx-pipeline build-notify --status started
      - dgx-pipeline npm login --token $GITHUB_TOKEN
      - npm ci

      # Run Nx Affected Test
      - dgx-pipeline nx gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        affected test
        --github-owner "$GITHUB_OWNER"
        --repository "$REPOSITORY_NAME" || true

      # Create GitHub Unit Test Checks
      - dgx-pipeline nx gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        commit create-unit-tests-checks
        --commit-id "$CODEBUILD_RESOLVED_SOURCE_VERSION"
        --github-owner "$GITHUB_OWNER"
        --repository "$REPOSITORY_NAME"
        --html-report-directory "html"

      # Create GitHub Code Coverage Checks
      - dgx-pipeline nx gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        commit publish-code-coverage-summary
        --github-owner "$GITHUB_OWNER"
        --html-report-directory "."
        --repository "$REPOSITORY_NAME"
        --commit-id "$CODEBUILD_RESOLVED_SOURCE_VERSION"
        --cobertura-xml-file "cobertura-coverage.xml"
        --clover-xml-file "clover.xml"
        --code-coverage-base-directory "coverage"
  post_build:
    commands:
      - dgx-pipeline build-notify --use-codebuild-env-var
