version: 0.2

env:
  shell: bash
  variables:
    CI: true
    PIP_DISABLE_PIP_VERSION_CHECK: true
    PIP_QUIET: true
    NODE_OPTIONS: '--max-old-space-size=8192'

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - aws codeartifact login --tool pip --repository dgx-shared-pypi-repo --domain dgx-shared-codeartifact --domain-owner $ACCOUNT_ID
      - pip install pipx==$PIPX_PACKAGE_VERSION
      # Add pipx binaries to path
      - export PATH="$PATH:/root/.local/bin"
      - aws codeartifact login --tool npm --repository dgx-shared-npm-repo --domain dgx-shared-codeartifact --domain-owner $ACCOUNT_ID
      - pipx install dgx-devops-pipeline-library==$PIPELINE_LIBRARY_PACKAGE_VERSION
  pre_build:
    commands:
      - dgx-pipeline build-init
      - dgx-pipeline build-notify --status started
      - dgx-pipeline npm login --token $GITHUB_TOKEN
      - npm ci

      # Add GitHub PR Labels
      - dgx-pipeline nx gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        pr apply-labels
        --pull-request-number "$CODEBUILD_SOURCE_VERSION"
        --github-owner "$GITHUB_OWNER"
        --repository "$REPOSITORY_NAME"
  build:
    commands:
      # Run NX Format GitHub Check
      - dgx-pipeline gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        commit create-cmd-check
        --commit-id "$CODEBUILD_RESOLVED_SOURCE_VERSION"
        --github-owner "$GITHUB_OWNER"
        --repository "$REPOSITORY_NAME"
        --command "npx --no-install nx format:check"
        --success-text "All files passed."
        --failure-text "The following files have formatting issues:"
        --check-name "nx format:check" || true

      # Run Nx Affected Lint
      - dgx-pipeline nx gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        affected lint
        --github-owner "$GITHUB_OWNER"
        --repository "$REPOSITORY_NAME" || true

      # Create GitHub ESLint Checks
      - dgx-pipeline nx gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        commit create-eslint-checks
        --commit-id "$CODEBUILD_RESOLVED_SOURCE_VERSION"
        --github-owner "$GITHUB_OWNER"
        --repository "$REPOSITORY_NAME"

      # Create NX Affected Changed Assets Files GitHub Check
      - dgx-pipeline nx gh
        --github-app-id "$GITHUB_APP_ID"
        --github-app-installation-id "$GITHUB_APP_INSTALLATION_ID"
        --github-app-private-key "$GITHUB_APP_PRIVATE_KEY"
        commit create-assets-change-check
        --github-owner "$GITHUB_OWNER"
        --repository "$REPOSITORY_NAME"
        --commit-id "$CODEBUILD_RESOLVED_SOURCE_VERSION"
        --filter "*.svg, *.png"
  post_build:
    commands:
      - dgx-pipeline build-notify --use-codebuild-env-var
